/**
 * Scaffold templates for coreline-agent conventions.
 */

import type {
  ScaffoldKind,
  ScaffoldNameParts,
  ScaffoldRenderedFileSpec,
  ScaffoldTemplateDefinition,
  ScaffoldTemplateFileSpec,
} from "./types.js";

function renderTemplate(template: string, tokens: Record<string, string>): string {
  let rendered = template;
  for (const [key, value] of Object.entries(tokens)) {
    rendered = rendered.replaceAll(`{{${key}}}`, value);
  }

  if (rendered.includes("{{")) {
    throw new Error(`Unresolved scaffold template token in "${template}"`);
  }

  return rendered;
}

function createTemplate(
  kind: ScaffoldKind,
  label: string,
  summary: string,
  files: ScaffoldTemplateFileSpec[],
  notes: string[],
): ScaffoldTemplateDefinition {
  return {
    kind,
    label,
    summary,
    files,
    notes,
  };
}

export const SCAFFOLD_TEMPLATES: Record<ScaffoldKind, ScaffoldTemplateDefinition> = {
  tool: createTemplate(
    "tool",
    "Tool",
    "Create a new tool module plus a focused test stub.",
    [
      {
        relativePathTemplate: "src/tools/{{kebab}}/{{kebab}}-tool.ts",
        description: "Tool implementation scaffold",
        contentTemplate: `/**
 * {{pascal}}Tool — scaffold generated by /scaffold.
 */

import { z } from "zod";
import { buildTool } from "../types.js";
import type { PermissionResult, ToolResult, ToolUseContext } from "../types.js";

export interface {{pascal}}Output {
  message: string;
}

export const {{pascal}}Tool = buildTool<Record<string, never>, {{pascal}}Output>({
  name: "{{pascal}}",
  description: "TODO: describe what this tool does.",
  inputSchema: z.object({}).strict(),

  checkPermissions: (): PermissionResult => ({ behavior: "ask" }),

  async call(_input: Record<string, never>, _context: ToolUseContext): Promise<ToolResult<{{pascal}}Output>> {
    return { data: { message: "TODO: implement {{pascal}} tool" } };
  },

  formatResult(output: {{pascal}}Output): string {
    return output.message;
  },
});
`,
      },
      {
        relativePathTemplate: "tests/{{kebab}}.test.ts",
        description: "Tool scaffold test stub",
        contentTemplate: `import { describe, expect, test } from "bun:test";

describe("{{kebab}} tool scaffold", () => {
  test("placeholder", () => {
    expect(true).toBe(true);
  });
});
`,
      },
    ],
    [
      "Generated tool files are colocated with the existing tool convention.",
      "Follow-up wiring can register the tool from src/tools/registry.ts.",
    ],
  ),

  provider: createTemplate(
    "provider",
    "Provider",
    "Create a provider module plus a focused test stub.",
    [
      {
        relativePathTemplate: "src/providers/{{kebab}}.ts",
        description: "Provider implementation scaffold",
        contentTemplate: `/**
 * {{pascal}}Provider — scaffold generated by /scaffold.
 *
 * Replace the stub with the provider-specific request/response adapter.
 */

export interface {{pascal}}ProviderOptions {
  readonly model?: string;
}

export interface {{pascal}}Provider {
  readonly name: string;
  readonly model: string;
}

export function create{{pascal}}Provider(options: {{pascal}}ProviderOptions = {}): {{pascal}}Provider {
  return {
    name: "{{kebab}}",
    model: options.model ?? "{{kebab}}",
  };
}
`,
      },
      {
        relativePathTemplate: "tests/{{kebab}}.test.ts",
        description: "Provider scaffold test stub",
        contentTemplate: `import { describe, expect, test } from "bun:test";

describe("{{kebab}} provider scaffold", () => {
  test("placeholder", () => {
    expect(true).toBe(true);
  });
});
`,
      },
    ],
    [
      "Generated provider files live beside the other providers.",
      "The main agent can later replace the stub with a full LLM adapter.",
    ],
  ),

  test: createTemplate(
    "test",
    "Test",
    "Create a standalone Bun test stub.",
    [
      {
        relativePathTemplate: "tests/{{kebab}}.test.ts",
        description: "Standalone test scaffold",
        contentTemplate: `import { describe, expect, test } from "bun:test";

describe("{{kebab}} scaffold", () => {
  test("placeholder", () => {
    expect(true).toBe(true);
  });
});
`,
      },
    ],
    [
      "Use this for quick test-only boilerplate.",
    ],
  ),

  "slash-command": createTemplate(
    "slash-command",
    "Slash command",
    "Create a command module stub that can later be wired into the TUI parser.",
    [
      {
        relativePathTemplate: "src/tui/scaffold/{{kebab}}.ts",
        description: "Slash-command module scaffold",
        contentTemplate: `/**
 * {{pascal}} slash-command scaffold.
 *
 * Wire this module into src/tui/slash-commands.ts once the command shape is finalized.
 */

export interface {{pascal}}SlashCommand {
  readonly command: string;
  readonly description: string;
}

export function create{{pascal}}SlashCommand(): {{pascal}}SlashCommand {
  return {
    command: "{{kebab}}",
    description: "TODO: describe the slash command.",
  };
}
`,
      },
      {
        relativePathTemplate: "tests/{{kebab}}.test.ts",
        description: "Slash-command scaffold test stub",
        contentTemplate: `import { describe, expect, test } from "bun:test";

describe("{{kebab}} slash-command scaffold", () => {
  test("placeholder", () => {
    expect(true).toBe(true);
  });
});
`,
      },
    ],
    [
      "This scaffold intentionally stops short of editing the shared parser file.",
      "The main agent can wire the generated module into src/tui/slash-commands.ts later.",
    ],
  ),

  hook: createTemplate(
    "hook",
    "Hook",
    "Create a hook module plus a focused test stub.",
    [
      {
        relativePathTemplate: "src/hooks/{{kebab}}.ts",
        description: "Hook implementation scaffold",
        contentTemplate: `/**
 * {{pascal}} hook scaffold.
 *
 * Replace the placeholder handler with the real event logic.
 */

import type { FunctionHookConfig } from "./types.js";

export const {{pascal}}Hook: FunctionHookConfig = {
  type: "function",
  event: "PreTool",
  name: "{{pascal}}",
  matcher: "*",
  handler: () => ({
    metadata: {
      note: "TODO: implement {{pascal}} hook",
    },
  }),
};
`,
      },
      {
        relativePathTemplate: "tests/{{kebab}}.test.ts",
        description: "Hook scaffold test stub",
        contentTemplate: `import { describe, expect, test } from "bun:test";

describe("{{kebab}} hook scaffold", () => {
  test("placeholder", () => {
    expect(true).toBe(true);
  });
});
`,
      },
    ],
    [
      "Hook scaffolds use the existing in-memory hook contract.",
      "The generated hook is intentionally conservative and easy to replace.",
    ],
  ),
};

export function getScaffoldTemplate(kind: ScaffoldKind): ScaffoldTemplateDefinition {
  return SCAFFOLD_TEMPLATES[kind];
}

function renderScaffoldTokens(name: ScaffoldNameParts, kind: ScaffoldKind): Record<string, string> {
  return {
    input: name.input,
    normalized: name.normalized,
    kebab: name.kebab,
    camel: name.camel,
    pascal: name.pascal,
    kind,
  };
}

export function renderScaffoldFiles(
  kind: ScaffoldKind,
  name: ScaffoldNameParts,
): ScaffoldRenderedFileSpec[] {
  const template = getScaffoldTemplate(kind);
  const tokens = renderScaffoldTokens(name, kind);

  return template.files.map((file) => ({
    relativePath: renderTemplate(file.relativePathTemplate, tokens),
    absolutePath: "",
    description: file.description,
    content: renderTemplate(file.contentTemplate, tokens),
  }));
}
