/**
 * Phase 3 (B5) — MEMORY.md digest boot tests.
 *
 * Covers:
 *  - TC-3.1: core + recent recall entries render in both sections (within budget).
 *  - TC-3.2: archival-only state yields "🔵 Archived (N)" with count line.
 *  - TC-3.3: oversized content is truncated with the MemKraft-compatible note.
 *  - TC-3.4: 30-day recent-cutoff excludes stale recall entries, includes fresh ones.
 *  - TC-3.5: empty project memory still emits a header + timestamp.
 *  - TC-3.E1: writeDigest against an un-writable path returns {written:false, error}.
 */

import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { renderDigest, writeDigest } from "../src/memory/digest.js";
import { ProjectMemory } from "../src/memory/project-memory.js";
import type { MemoryEntry } from "../src/memory/types.js";

function isoDaysAgo(days: number): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString().slice(0, 10);
}

function seedEntry(
  projectMemory: ProjectMemory,
  overrides: Partial<MemoryEntry> & Pick<MemoryEntry, "name" | "description">,
): void {
  projectMemory.writeEntry({
    name: overrides.name,
    description: overrides.description,
    type: overrides.type ?? "project",
    body: overrides.body ?? `Body of ${overrides.name}`,
    filePath: overrides.filePath ?? "",
    tier: overrides.tier,
    lastAccessed: overrides.lastAccessed,
    accessCount: overrides.accessCount,
    importance: overrides.importance,
  });
}

describe("MEMORY.md digest (Phase 3)", () => {
  let rootDir: string;
  let workspace: string;
  let projectMemory: ProjectMemory;

  beforeEach(() => {
    rootDir = mkdtempSync(join(tmpdir(), "digest-test-"));
    workspace = mkdtempSync(join(tmpdir(), "digest-ws-"));
    mkdirSync(join(workspace, ".git"), { recursive: true });
    writeFileSync(join(workspace, "AGENT.md"), "# Rules\nRun Bun.");
    projectMemory = new ProjectMemory(workspace, { rootDir });
  });

  afterEach(() => {
    rmSync(rootDir, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  });

  // -------------------------------------------------------------------------
  // TC-3.1: 5 core + 8 recent recall entries; maxChars=15000 → both sections
  // included in full, counts match, truncated=false.
  // -------------------------------------------------------------------------
  test("TC-3.1: renders both core and recent-recall sections within budget", () => {
    for (let i = 0; i < 5; i++) {
      seedEntry(projectMemory, {
        name: `core_entry_${i}`,
        description: `core desc ${i}`,
        tier: "core",
        lastAccessed: isoDaysAgo(2),
      });
    }
    for (let i = 0; i < 8; i++) {
      seedEntry(projectMemory, {
        name: `recall_entry_${i}`,
        description: `recall desc ${i}`,
        tier: "recall",
        lastAccessed: isoDaysAgo(5),
      });
    }

    const result = renderDigest({ projectMemory, maxChars: 15_000 });

    expect(result.truncated).toBe(false);
    expect(result.coreCount).toBe(5);
    expect(result.recallRecentCount).toBe(8);
    expect(result.archivalCount).toBe(0);
    expect(result.content).toContain("# MEMORY.md — Auto-generated by coreline-agent");
    expect(result.content).toContain("## 🔴 Core Memory");
    expect(result.content).toContain("## 🟡 Recent Memory (30d)");
    expect(result.content).not.toContain("## 🔵 Archived");
    for (let i = 0; i < 5; i++) {
      expect(result.content).toContain(`core_entry_${i}: core desc ${i}`);
    }
    for (let i = 0; i < 8; i++) {
      expect(result.content).toContain(`recall_entry_${i}: recall desc ${i}`);
    }
  });

  // -------------------------------------------------------------------------
  // TC-3.2: 0 core + 0 recall + 50 archival → emits "🔵 Archived (50)" count line.
  // No 🔴/🟡 sections.
  // -------------------------------------------------------------------------
  test("TC-3.2: archival-only state emits count line and omits other sections", () => {
    for (let i = 0; i < 50; i++) {
      seedEntry(projectMemory, {
        name: `archived_${i}`,
        description: `arch desc ${i}`,
        tier: "archival",
      });
    }

    const result = renderDigest({ projectMemory });

    expect(result.coreCount).toBe(0);
    expect(result.recallRecentCount).toBe(0);
    expect(result.archivalCount).toBe(50);
    expect(result.content).not.toContain("## 🔴 Core Memory");
    expect(result.content).not.toContain("## 🟡 Recent Memory");
    expect(result.content).toContain("## 🔵 Archived (50)");
    expect(result.content).toContain("50 entities archived.");
  });

  // -------------------------------------------------------------------------
  // TC-3.3: maxChars=500 with heavy content forces truncation note.
  // -------------------------------------------------------------------------
  test("TC-3.3: truncates with MemKraft-compatible note when exceeding budget", () => {
    const bigDesc = "x".repeat(400);
    for (let i = 0; i < 20; i++) {
      seedEntry(projectMemory, {
        name: `core_big_${i}`,
        description: `${bigDesc}_${i}`,
        tier: "core",
      });
    }

    const result = renderDigest({ projectMemory, maxChars: 500 });

    expect(result.truncated).toBe(true);
    expect(result.content.trimEnd().endsWith("full output]*")).toBe(true);
    expect(result.content).toContain("*[digest truncated");
    expect(result.chars).toBeLessThanOrEqual(500);
  });

  // -------------------------------------------------------------------------
  // TC-3.4: recall entry with lastAccessed older than 30d is NOT rendered
  // in the "Recent Memory (30d)" bullet list; fresh recall entry IS rendered.
  // -------------------------------------------------------------------------
  test("TC-3.4: 30-day recency cutoff filters stale recall entries", () => {
    seedEntry(projectMemory, {
      name: "stale_recall",
      description: "old entry",
      tier: "recall",
      lastAccessed: isoDaysAgo(60),
    });
    seedEntry(projectMemory, {
      name: "fresh_recall",
      description: "new entry",
      tier: "recall",
      lastAccessed: isoDaysAgo(3),
    });

    const result = renderDigest({ projectMemory });

    expect(result.recallRecentCount).toBe(1);
    expect(result.content).toContain("fresh_recall: new entry");
    expect(result.content).not.toContain("stale_recall");
  });

  // -------------------------------------------------------------------------
  // TC-3.5: Empty project memory → header + timestamp only, but non-empty output.
  // -------------------------------------------------------------------------
  test("TC-3.5: empty project memory emits header + timestamp", () => {
    const result = renderDigest({ projectMemory });

    expect(result.chars).toBeGreaterThan(0);
    expect(result.content).toContain("# MEMORY.md — Auto-generated by coreline-agent");
    expect(result.content).toContain("**Updated:**");
    expect(result.content).toContain("KST");
    expect(result.coreCount).toBe(0);
    expect(result.recallRecentCount).toBe(0);
    expect(result.archivalCount).toBe(0);
    expect(result.truncated).toBe(false);
  });

  // -------------------------------------------------------------------------
  // TC-3.E1: writeDigest to an un-writable path returns {written:false, error}
  // and never throws. We force failure by pointing rootDir at an existing file
  // so that {rootDir}/projects/... cannot be created as a directory.
  // -------------------------------------------------------------------------
  test("TC-3.E1: writeDigest returns error status on I/O failure", () => {
    const blockingFile = join(
      mkdtempSync(join(tmpdir(), "digest-block-")),
      "blocker",
    );
    writeFileSync(blockingFile, "not a directory");

    // rootDir = a regular file → mkdir + writeFile below will both fail.
    const result = writeDigest({
      projectId: "proj_abcdef",
      content: "# hello",
      rootDir: blockingFile,
    });

    expect(result.written).toBe(false);
    expect(typeof result.error).toBe("string");
    expect(result.error?.length ?? 0).toBeGreaterThan(0);

    rmSync(blockingFile, { force: true });
  });
});
