/**
 * Wave 10 P3 O4 — Broad-coverage frontmatter snapshot tests.
 *
 * Loads every `.md` fixture under tests/fixtures/frontmatter-snapshots/ and
 * asserts that `parseMemoryFile → extractExtendedFields → serializeMemoryFile`
 * produces a byte-identical result and a stable extended-fields projection.
 *
 * Fixtures are generated by `scripts/generate-frontmatter-fixtures.ts`
 * using the real `serializeMemoryFile` so any future parser/serializer drift
 * across the 14+ frontmatter fields surfaces here immediately.
 */

import { describe, expect, test } from "bun:test";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  parseMemoryFile,
  serializeMemoryFile,
  extractExtendedFields,
} from "../src/memory/memory-parser.js";
import type { MemoryType } from "../src/memory/types.js";

const FIXTURE_DIR = join(import.meta.dir, "fixtures", "frontmatter-snapshots");

describe("Frontmatter snapshot broad coverage (O4)", () => {
  const fixtures = readdirSync(FIXTURE_DIR)
    .filter((f) => f.endsWith(".md"))
    .sort();

  for (const fixture of fixtures) {
    test(`${fixture} — parse → serialize is byte-identical`, () => {
      const original = readFileSync(join(FIXTURE_DIR, fixture), "utf-8");
      const { frontmatter, body } = parseMemoryFile(original);
      const extended = extractExtendedFields(frontmatter);

      const serialized = serializeMemoryFile({
        name: String(frontmatter.name ?? ""),
        description: String(frontmatter.description ?? ""),
        type: frontmatter.type as MemoryType,
        body,
        ...extended,
      });

      expect(serialized).toBe(original);
    });

    test(`${fixture} — parse → readEntry-like flow preserves all known fields`, () => {
      const original = readFileSync(join(FIXTURE_DIR, fixture), "utf-8");
      const { frontmatter, body } = parseMemoryFile(original);
      const ext1 = extractExtendedFields(frontmatter);

      const reserialized = serializeMemoryFile({
        name: String(frontmatter.name ?? ""),
        description: String(frontmatter.description ?? ""),
        type: frontmatter.type as MemoryType,
        body,
        ...ext1,
      });
      const { frontmatter: fm2 } = parseMemoryFile(reserialized);
      const ext2 = extractExtendedFields(fm2);

      // Idempotent: extended fields survive a second roundtrip unchanged.
      expect(ext2).toEqual(ext1);
    });
  }
});
