/**
 * MEMORY.md digest renderer — snapshot of project memory by tier.
 * Port of MemKraft lifecycle.py:250-333.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { DEFAULT_TIER } from "./constants.js";
import { tierList } from "./tiering.js";
import { getDigestPath } from "../config/paths.js";
import type { MemoryEntry, MemoryTier, ProjectMemoryCore } from "./types.js";

export interface RenderDigestOptions {
  projectMemory: ProjectMemoryCore;
  /** Max output size in chars. Default 15000. */
  maxChars?: number;
  /** Cutoff for "Recent" recall section (days). Default 30. */
  recentDays?: number;
}

export interface RenderDigestResult {
  content: string;
  chars: number;
  truncated: boolean;
  coreCount: number;
  recallRecentCount: number;
  archivalCount: number;
}

const DEFAULT_MAX_CHARS = 15_000;
const DEFAULT_RECENT_DAYS = 30;
const TRUNCATION_NOTE = "\n\n*[digest truncated — run mk.digest() for full output]*\n";

function formatKstTimestamp(now: Date): string {
  // "sv-SE" yields YYYY-MM-DD HH:MM:SS ... using Asia/Seoul timezone.
  const formatted = now.toLocaleString("sv-SE", {
    timeZone: "Asia/Seoul",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
  // Expected shape: "YYYY-MM-DD HH:MM"
  return `${formatted.replace("T", " ").slice(0, 16)} KST`;
}

function tierOf(entry: MemoryEntry): MemoryTier {
  return entry.tier ?? DEFAULT_TIER;
}

function isWithinRecentDays(lastAccessed: string | undefined, recentDays: number, now: Date): boolean {
  if (!lastAccessed) {
    return false;
  }
  // lastAccessed is YYYY-MM-DD.
  const parsed = Date.parse(`${lastAccessed}T00:00:00Z`);
  if (Number.isNaN(parsed)) {
    return false;
  }
  const ageDays = (now.getTime() - parsed) / (1000 * 60 * 60 * 24);
  return ageDays <= recentDays;
}

function renderBulletList(entries: MemoryEntry[]): string {
  const lines: string[] = [];
  for (const entry of entries) {
    const desc = entry.description?.trim() || "(no description)";
    lines.push(`- ${entry.name}: ${desc}`);
  }
  return lines.join("\n");
}

export function renderDigest(options: RenderDigestOptions): RenderDigestResult {
  const maxChars = options.maxChars ?? DEFAULT_MAX_CHARS;
  const recentDays = options.recentDays ?? DEFAULT_RECENT_DAYS;
  const now = new Date();

  const all = tierList(options.projectMemory);
  const coreEntries = all.filter((e) => tierOf(e) === "core");
  const recallEntries = all.filter((e) => tierOf(e) === "recall");
  const archivalEntries = all.filter((e) => tierOf(e) === "archival");

  const recallRecent = recallEntries.filter((e) =>
    isWithinRecentDays(e.lastAccessed, recentDays, now),
  );

  const coreCount = coreEntries.length;
  const recallRecentCount = recallRecent.length;
  const archivalCount = archivalEntries.length;

  const sections: string[] = [];
  let totalChars = 0;

  const header =
    `# MEMORY.md — Auto-generated by coreline-agent\n` +
    `**Updated:** ${formatKstTimestamp(now)} | **Source:** coreline-agent digest\n\n`;
  sections.push(header);
  totalChars += header.length;

  // Budget reservations scale with maxChars so tiny budgets still attempt
  // to write content (and truncate downstream if they overflow).
  const coreReserve = Math.min(2000, Math.floor(maxChars * 0.15));
  const recallReserve = Math.min(1500, Math.floor(maxChars * 0.1));
  const archivalReserve = Math.min(200, Math.floor(maxChars * 0.05));

  // Core section
  if (coreCount > 0 && totalChars < maxChars - coreReserve) {
    const body = renderBulletList(coreEntries);
    const block = `## 🔴 Core Memory\n\n${body}\n\n`;
    sections.push(block);
    totalChars += block.length;
  }

  // Recall section (30d)
  if (recallRecentCount > 0 && totalChars < maxChars - recallReserve) {
    const body = renderBulletList(recallRecent);
    const block = `## 🟡 Recent Memory (${recentDays}d)\n\n${body}\n\n`;
    sections.push(block);
    totalChars += block.length;
  }

  // Archival count only
  if (archivalCount > 0 && totalChars < maxChars - archivalReserve) {
    const block =
      `## 🔵 Archived (${archivalCount})\n\n` +
      `${archivalCount} entities archived. Run MemoryRecall to retrieve.\n\n`;
    sections.push(block);
    totalChars += block.length;
  }

  let output = sections.join("");
  let truncated = false;

  if (output.length > maxChars) {
    const keep = Math.max(0, maxChars - TRUNCATION_NOTE.length);
    output = output.slice(0, keep) + TRUNCATION_NOTE;
    truncated = true;
  }

  return {
    content: output,
    chars: output.length,
    truncated,
    coreCount,
    recallRecentCount,
    archivalCount,
  };
}

export interface WriteDigestOptions {
  projectId: string;
  content: string;
  rootDir?: string;
}

export interface WriteDigestResult {
  written: boolean;
  path?: string;
  error?: string;
}

/** Best-effort write to ~/.coreline-agent/projects/{projectId}/MEMORY.md. */
export function writeDigest(options: WriteDigestOptions): WriteDigestResult {
  try {
    if (!options.projectId) {
      return { written: false, error: "projectId is required" };
    }
    const path = getDigestPath(options.projectId, options.rootDir);
    try {
      mkdirSync(dirname(path), { recursive: true });
    } catch {
      // Best-effort: swallow mkdir errors — the subsequent write will surface the real issue.
    }
    writeFileSync(path, options.content, { encoding: "utf-8" });
    return { written: true, path };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { written: false, error: message };
  }
}
